### ISSUE TITLE
Create low fidelity prototype

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-TimeBolinho#18]
### Description:

Create low fidelity prototype on paper to help understand product and users needs.

### Acceptance standards:

- Prototype must reflect all functional requirements
- All development team members must participate on this prototype development
- This prototype must be on paper

### Tasks:

- [ ]  Create screens for harversters user

- [ ] Create screens for tree owner user

- [ ] Create harversters leader screens

- [ ] Create screens for recipients

**Comment by shayanealcantara** [comment]
Algumas ferramentas úteis pra desenvolver a protótipo: 
- Figma
- Quant UX
- Marvel
- ...

**Comment by fabiolamfleury** [comment]
Para realização do protótipo, foi apresentado o contexto do produto para a equipe de MDS, no dia 31/08, bem como o termo de abertura desenvolvido.

**Comment by RenatoBrittoAraujo** [comment]
A gente está considerando fazer apenas no papel, para levar em conta apenas das mecânicas do site de maneira rápida passando por algums iterações. Tem problema pular a parte de usar as ferramentas listadas e ficar apenas no papel?

**Comment by fabiolamfleury** [comment]
> A gente está considerando fazer apenas no papel, para levar em conta apenas das mecânicas do site de maneira rápida passando por algums iterações. Tem problema pular a parte de usar as ferramentas listadas e ficar apenas no papel?

As ferramentas sugeridas são utilizadas na verdade pra protótipo de alta fidelidade :) como descrito na issue, um dos critérios de aceitação é ser feito em papel mesmo

**Comment by LeoSilvaGomes** [comment]
No dia 31/08, foi desenvolvido pela equipe de MDS um brainstorm para o desenvolvimento de protótipo de baixa qualidade, no qual demos inicio a algumas decisões e encaminhamentos para a finalização do protótipo. Mediante isso, cada aluno, após as discussões, tiveram seu tempo de consolidar seus pensamentos em um protótipo, onde quinta-feira (05/09), daremos continuidade as discussões e a possibilidade de termino da issue.

Segue alguns dos trabalhos feitos pelos membros da equipe:

![New Doc 2019-09-03 23 59 35_3](https://user-images.githubusercontent.com/38738836/64223015-95872380-cea8-11e9-9866-f4d98a383f50.jpg)
![New Doc 2019-09-03 23 59 35_5](https://user-images.githubusercontent.com/38738836/64223016-95872380-cea8-11e9-8f0e-b2bb5be5dae4.jpg)
![New Doc 2019-09-03 23 59 35_4](https://user-images.githubusercontent.com/38738836/64223018-961fba00-cea8-11e9-9832-cf90555eaf8f.jpg)
Documento feito por @RenatoBrittoAraujo 

![New Doc 2019-09-03 23 59 35_6](https://user-images.githubusercontent.com/38738836/64223017-95872380-cea8-11e9-9c40-84deaf80e362.jpg)
![New Doc 2019-09-03 23 59 35_7](https://user-images.githubusercontent.com/38738836/64223020-961fba00-cea8-11e9-95f1-583830d9246f.jpg)
Documento feito por @LeoSilvaGomes 

![New Doc 2019-09-03 23 59 35_1](https://user-images.githubusercontent.com/38738836/64223021-961fba00-cea8-11e9-9670-6108f45cb30b.jpg)
![New Doc 2019-09-03 23 59 35_2](https://user-images.githubusercontent.com/38738836/64223022-961fba00-cea8-11e9-8e7b-8b053ae0634b.jpg)
Documento feito por @durvalcarvalho 


Os documentos pendentes nesse comentário, imaginasse que esteja com os membros em que a folha pertence.

**Comment by RenatoBrittoAraujo** [comment]
No dia 05/09 Ocorreu uma reunião entre os integrantes de MDS para decidir quais são as telas e o conteúdo delas. Aqui estão alguns dos resultados dessa reunião. O protótipo de baixa fidelidade ainda não está completo.

Sobre o flow dos usuários usando o site
![20190905_135057](https://user-images.githubusercontent.com/45462822/64384688-7903fc00-d00c-11e9-8a9d-34a97643de00.jpg)

Página home
![20190905_182929](https://user-images.githubusercontent.com/45462822/64384692-7903fc00-d00c-11e9-849d-95df40310eec.jpg)

Dashboard
![20190905_183454](https://user-images.githubusercontent.com/45462822/64384700-799c9280-d00c-11e9-8f96-de61605cfa3e.jpg)

Página de colheita
![20190905_182945](https://user-images.githubusercontent.com/45462822/64384695-7903fc00-d00c-11e9-9e32-b55aa2a6bbec.jpg)

Página de dados sobre colhietas
![20190905_182954](https://user-images.githubusercontent.com/45462822/64384697-7903fc00-d00c-11e9-9e51-da33ae2c9404.jpg)

**Comment by durvalcarvalho** [comment]
Protótipo de baixa qualidade discutido na reunião do dia 05/09
![photo5157020846840195194](https://user-images.githubusercontent.com/31013187/64442771-dc426c80-d0a6-11e9-931a-1be475a61dbd.jpg)
![photo5159101440667527214](https://user-images.githubusercontent.com/31013187/64442779-de0c3000-d0a6-11e9-8b50-ff6c9003a464.jpg)
![photo5157020846840195193](https://user-images.githubusercontent.com/31013187/64442792-dfd5f380-d0a6-11e9-9120-9b069fb095be.jpg)

**Comment by LeoSilvaGomes** [comment]
#### Task: criar uma tela para beneficiários 
Discutimos isso em nossas reuniões e concluímos que como o beneficiário não participa diretamente do processo que o contexto do site está envolvido, pois ele é a a finalidade da causa, vimos eles apenas como informações para o voluntário. Em suma, não vimos necessidade da criação de página(s) exclusiva(s) para os beneficiários.

Essa informação procede? @fabiolamfleury

**Comment by durvalcarvalho** [comment]
Protótipo de baixa qualidade desenhado pelo @RenatoBrittoAraujo após as decisões tomadas na reunião do dia 05/09
![photo5159185420163065866](https://user-images.githubusercontent.com/31013187/64466487-c35aab00-d0e8-11e9-8c6e-a75999fb2e8b.jpg)
![photo5159185420163065868](https://user-images.githubusercontent.com/31013187/64466491-c6ee3200-d0e8-11e9-911d-3b8c27d613a2.jpg)
![photo5159185420163065867](https://user-images.githubusercontent.com/31013187/64466493-c81f5f00-d0e8-11e9-9e41-78a87a363880.jpg)

**Comment by fabiolamfleury** [comment]
Ficou faltando na descrição da issue, mas por favor documentem isso. Criem um documento na pasta docs, markdown, e coloquem ao menos um título pra cada imagem de uma página. Só as imagens fica muito dificil de entender sem ter participado da construção do protótipo

**Comment by jps12** [comment]
Como será a primeira tela do site (url /), será uma tela sobre o projeto (about) ou será a página de dashboard? Como você, @fabiolamfleury, imagina a primeira página.

**Comment by fabiolamfleury** [comment]
Acho que a tela que vocês fizeram que se aproxima mais de um / é essa (pensando que ela deve apresentar o projeto e atrair pessoas a utilizarem):

Mas, para um usuário logado, seria interessante ir direto para dashboard

![image](https://user-images.githubusercontent.com/20935369/64546040-40ac3880-d300-11e9-8ba8-3199fc0a2394.png)

**Comment by jps12** [comment]
Onde o tipo de conta do usuário (voluntário ou owner) é definido? Um voluntário poderá registrar uma propriedade ou um owner vai poder participar de uma colheita? Os tipos de conta são fixos ou fluídos no sentido de que o mesmo usuário pode ter várias funções no site?

**Comment by fabiolamfleury** [comment]
O que vocês acham? É interessante pra facilitar para o usuário ser muito simples de cadastrar: pedir dados apenas como nome, email e senha. Depois, avisar que ele pode completar os dados dele colocando que ele é dono ou quer se voluntariar para uma colheita. Acredito que o usuário pode ser ambos, um ou outro ou nenhum dos dois

**Comment by KiSobral** [comment]
No dia 09/09, o grupo de MDS se reuniu presencialmente, no horário do almoço, para terminar de definir os fluxos de uso e desenhar as telas no papel para o protótipo de baixa fidelidade.

O resultado destas telas deu-se por:
![prototipo_baixa_1](https://user-images.githubusercontent.com/43852963/64743085-e2847e80-d4d4-11e9-94b6-88eaf820cd7e.jpg)
![prototipo_baixa_2](https://user-images.githubusercontent.com/43852963/64743093-ea442300-d4d4-11e9-9d01-9c0d505e4a8a.jpg)
