### ISSUE TITLE
Create repository policies

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-TimeBolinho#7]
### Description:

- Create repository policies to organize project

### Acceptance standards:

- Policies are known by all team

### Tasks:

- [x]  Create branch policy

- [x] Create commit policy

- [ ] Train team to use policies

**Comment by vitorcx** [comment]
Please take a look at the first version of the repository policies, so you can give me some feedback or suggestions. @fabiolamfleury @MarthaDs @shayanealcantara 
[Repository Policies](https://github.com/fga-eps-mds/2019.2-TimeBolinho/blob/master/docs/policies.md)
